import { Component, ElementRef, ViewChild, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { Navbar } from '../../components/navbar/navbar';

interface Message {
  id: number;
  sender: 'user' | 'assistant';
  text: string;
  time: string;
  isItinerary?: boolean;
  itineraryData?: Itinerary;
}

interface Itinerary {
  destination: string;
  duration: string;
  budget: string;
  days: {
    dayNum: number;
    title: string;
    activities: string[];
  }[];
}

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, Navbar],
  templateUrl: './chat.html',
  styleUrl: './chat.css'
})
export class ChatPage implements AfterViewChecked {
  @ViewChild('scrollContainer') private scrollContainer!: ElementRef;

  newMessageText: string = '';
  isAssistantTyping: boolean = false;

  suggestions: string[] = [
    'Plan a 3-day cultural tour in Rome',
    'Suggest a budget-friendly week in Tokyo',
    'Generate a luxury 5-day escape to Maldives',
    'Recommend food spots and cafes in Paris'
  ];

  chatHistory = [
    { id: 1, title: 'Summer in Paris Plan', date: 'June 15, 2026' },
    { id: 2, title: 'Rome 4-Day History Tour', date: 'June 10, 2026' },
    { id: 3, title: 'Maldives Beach Getaway', date: 'May 28, 2026' }
  ];

  messages: Message[] = [
    {
      id: 1,
      sender: 'assistant',
      text: 'Hi, I am your TripMind AI co-pilot. Tell me where you want to go, how long you have, and the travel style you prefer.',
      time: '03:00 AM'
    }
  ];

  ngAfterViewChecked() {
    this.scrollToBottom();
  }

  scrollToBottom(): void {
    try {
      this.scrollContainer.nativeElement.scrollTop = this.scrollContainer.nativeElement.scrollHeight;
    } catch (err) {}
  }

  sendMessage() {
    if (!this.newMessageText.trim()) return;

    const userText = this.newMessageText;
    const userTime = this.getCurrentTime();
    
    // Add user message
    this.messages.push({
      id: this.messages.length + 1,
      sender: 'user',
      text: userText,
      time: userTime
    });

    this.newMessageText = '';
    this.isAssistantTyping = true;

    // Simulate backend response from Semantic Kernel
    setTimeout(() => {
      this.isAssistantTyping = false;
      const responseText = this.generateAIResponse(userText);
      const isItinerary = responseText.includes('ITINERARY:');
      let cleanText = responseText;
      let itineraryData: Itinerary | undefined;

      if (isItinerary) {
        cleanText = 'Here is the detailed itinerary generated by our Semantic Kernel AI planner:';
        itineraryData = this.parseMockItinerary(userText);
      }

      this.messages.push({
        id: this.messages.length + 1,
        sender: 'assistant',
        text: cleanText,
        time: this.getCurrentTime(),
        isItinerary: isItinerary,
        itineraryData: itineraryData
      });
    }, 1500);
  }

  selectSuggestion(prompt: string) {
    this.newMessageText = prompt;
    this.sendMessage();
  }

  startNewChat() {
    this.messages = [
      {
        id: 1,
        sender: 'assistant',
        text: 'Fresh journey started. Share a destination, dates, budget, or the kind of experience you want.',
        time: this.getCurrentTime()
      }
    ];
  }

  private getCurrentTime(): string {
    const now = new Date();
    let hours = now.getHours();
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12;
    hours = hours ? hours : 12; // 0 should be 12
    return `${hours}:${minutes} ${ampm}`;
  }

  private generateAIResponse(userInput: string): string {
    const input = userInput.toLowerCase();
    if (input.includes('rome') || input.includes('italy')) {
      return 'ITINERARY: Rome';
    } else if (input.includes('tokyo') || input.includes('japan')) {
      return 'ITINERARY: Tokyo';
    } else if (input.includes('maldives')) {
      return 'ITINERARY: Maldives';
    } else if (input.includes('paris') || input.includes('france')) {
      return 'ITINERARY: Paris';
    } else if (input.includes('budget') || input.includes('cost')) {
      return 'Based on your request, I recommend focusing on public transportation and local street vendors. I can draft an optimized budget breakdown if you specify the destination and duration!';
    } else {
      return 'I received your request! Let me coordinate with our multi-agent planners. Could you please specify your preferred travel dates, average nightly budget, or specific sights you definitely want to visit?';
    }
  }

  private parseMockItinerary(userInput: string): Itinerary {
    const input = userInput.toLowerCase();
    if (input.includes('rome')) {
      return {
        destination: 'Rome, Italy',
        duration: '3 Days',
        budget: 'EUR 450 (Moderate)',
        days: [
          {
            dayNum: 1,
            title: 'Ancient Rome Explorations',
            activities: ['Visit Colosseum & Roman Forum', 'Gelato break near Piazza Navona', 'Walk up the Spanish Steps', 'Dinner in Trastevere district']
          },
          {
            dayNum: 2,
            title: 'Vatican City & Renaissance Art',
            activities: ['Guided tour of Vatican Museums & St. Peter\'s Basilica', 'Stroll along Castel Sant\'Angelo', 'Make a wish at Trevi Fountain']
          },
          {
            dayNum: 3,
            title: 'Scenic Views & Roman Culture',
            activities: ['Explore Villa Borghese Gardens & Galleria', 'Panoramic views from Janiculum Hill', 'Enjoy traditional Pasta Carbonara class']
          }
        ]
      };
    } else if (input.includes('tokyo')) {
      return {
        destination: 'Tokyo, Japan',
        duration: '7 Days',
        budget: 'JPY 120,000 (Budget-friendly)',
        days: [
          {
            dayNum: 1,
            title: 'Modern Marvels of Shinjuku',
            activities: ['Arrive in Tokyo, explore Shinjuku Golden Gai', 'Panoramic view from Tokyo Metropolitan Government Bldg']
          },
          {
            dayNum: 2,
            title: 'Tradition meets Pop Culture',
            activities: ['Visit Senso-ji Temple in Asakusa', 'Shopping in Akihabara Electric Town', 'Stroll through Ueno Park']
          },
          {
            dayNum: 3,
            title: 'Youth Culture & Trendy Districts',
            activities: ['Walk Shibuya Crossing', 'Visit Meiji Shrine & Harajuku Takeshita Street', 'Dinner in Omotesando']
          }
        ]
      };
    } else if (input.includes('maldives')) {
      return {
        destination: 'Maldives Island Resort',
        duration: '5 Days',
        budget: '$2,800 (Premium Luxury)',
        days: [
          {
            dayNum: 1,
            title: 'Tropical Welcome',
            activities: ['Speedboat transfer to Overwater Villa', 'Welcome drinks & sunset beach walk', 'Private deck dining']
          },
          {
            dayNum: 2,
            title: 'Underwater Adventures',
            activities: ['Morning guided snorkeling safari', 'Relaxing Balinese spa treatment', 'Beachside cinema screening']
          },
          {
            dayNum: 3,
            title: 'Local Culture & Sailing',
            activities: ['Sunset catamaran cruise with dolphin watching', 'Traditional Maldivian night & buffet']
          }
        ]
      };
    } else {
      // Default Paris
      return {
        destination: 'Paris, France',
        duration: '4 Days',
        budget: 'EUR 680 (Moderate)',
        days: [
          {
            dayNum: 1,
            title: 'Iconic Monuments',
            activities: ['Eiffel Tower summit access', 'Seine River sightseeing cruise', 'Stroll along Champs-Elysees']
          },
          {
            dayNum: 2,
            title: 'Art & Bohemian Vibes',
            activities: ['Visit Louvre Museum', 'Walk up Montmartre hill & Sacre-Coeur', 'Cafe dining in Latin Quarter']
          },
          {
            dayNum: 3,
            title: 'Royal Gardens & Strolling',
            activities: ['Palace of Versailles day trip', 'Relax at Jardin du Luxembourg', 'Dinner at a traditional French bistro']
          }
        ]
      };
    }
  }
}
